### ISSUE TITLE
Essencial: remover categorias inativas

### ISSUE THREAD

**Issue by cacio-costa** [lucasbiazin/Comex#2]
Biazin, a exclusão funcionou perfeitamente. Só tem um detalhe pequeno: a tarefa pedia para remover as categorias INATIVA, e aqui está removendo pelo ID.

E como trata-se de operação no banco de dados, o ideal é criar um método `deletaInativas` em `CategoriaDao`.

https://github.com/lucasbiazin/Comex/blob/e7dd7fd2603f3c9a5a84e3b13c55594ff42320f9/src/br/com/comex/dao/main/categoria/MainTestaRemocaoCategoria.java#L18

Vou deixar como entrega parcial por enquanto, mas quando ajustar, me avise. ;)

**Comment by lucasbiazin** [comment]
Feito!
