### ISSUE TITLE
Codificar remoção no CRUD de cliente

### ISSUE THREAD

**Issue by cacio-costa** [lucasbiazin/Comex#3]
Faltou o código de remoção, Biazin.

https://github.com/lucasbiazin/Comex/blob/e7dd7fd2603f3c9a5a84e3b13c55594ff42320f9/src/br/com/comex/dao/main/cliente/TesteRemocaoCliente.java#L6

O CRUD de Clientes vai ficar parcial. ;)

**Comment by lucasbiazin** [comment]
Feito !!
