### ISSUE TITLE
Não setou ID para alterar Cliente

### ISSUE THREAD

**Issue by cacio-costa** [lucasbiazin/Comex#4]
Mestre Biazin, uma coisa importante. Achei **TOP** você ter usado o `AtomicInteger` para controlar a geração de IDs. Código resiliente à concorrência. Parabéns mesmo!!!

https://github.com/lucasbiazin/Comex/blob/e7dd7fd2603f3c9a5a84e3b13c55594ff42320f9/src/br/com/comex/modelo/Cliente.java#L26

Mas agora que o projeto usa o banco de dados, que gera os IDs, pode-se remover esse controle manual. Inclusive, o ID pode ser setado erroneamente, e gerar erro de lógica durante a execução do programa.

Foi o que aconteceu ao alterar o Cliente. Você não setou o ID no construtor, foi atribuído o ID#1, e apesar da mensagem de sucesso, o registro não foi alterado no banco de dados. Poderia ter sido alterado um registro equivocadamente.

https://github.com/lucasbiazin/Comex/blob/e7dd7fd2603f3c9a5a84e3b13c55594ff42320f9/src/br/com/comex/dao/main/cliente/MainTestaUpdateCliente.java#L19

Então, fica um ajuste futuro de remover esse controle de ID das entidades. ;)

**Comment by lucasbiazin** [comment]
Po Cácio, obrigado pelo retorno.. Já era para eu ter retirado mesmo. Acabei
esquecendo.


Mas do mais, tá ok ?

Em qua., 19 de out. de 2022 às 14:56, Cácio Costa ***@***.***>
escreveu:
