### ISSUE TITLE
Corrigir definição de descontos em ItemPedido

### ISSUE THREAD

**Issue by cacio-costa** [lucasbiazin/Comex#5]
Biazin, aqui a gente tem um pequeno detalhe de lógica. Você está definindo o desconto do objeto `ItemPedido` criado na linha 20 a partir de **outro ItemPedido** criado na linha 18.

https://github.com/lucasbiazin/Comex/blob/e7dd7fd2603f3c9a5a84e3b13c55594ff42320f9/src/br/com/comex/dao/main/itemPedido/MainTestaInsereItemPedido.java#L18-L20

Para inicializar corretamente o desconto do `ItemPedido`, no seu código, teria que chamar o método `filtraDescontos()` **dentro do construtor**. Ficaria assim:
```java
public ItemPedido(double precoUnitario, int quantidade, Produto produtoItemPedido, Pedido pedido, double desconto, int tipoDesconto) {
    this.id = count.incrementAndGet(); // tira isso daqui depois hehehe
    this.precoUnitario = precoUnitario;
    this.quantidade = quantidade;
    this.produtoItemPedido = produtoItemPedido;
    this.pedido = pedido;

    this.tipoDesconto = tipoDesconto; // define o tipo de desconto
    this.desconto = this.filtraDescontos(); // agora sim, cada objeto vai ser inicializado de acordo com **seu** desconto
}

https://github.com/lucasbiazin/Comex/blob/e7dd7fd2603f3c9a5a84e3b13c55594ff42320f9/src/br/com/comex/modelo/ItemPedido.java#L24-35

**Comment by lucasbiazin** [comment]
Opa.. Já corrigi kk
