### ISSUE TITLE
Parabéns pelo código!!!

### ISSUE THREAD

**Issue by cacio-costa** [lucasbiazin/Comex#6]
Biazin, permita-me elogiá-lo!!! 

Seu projeto foi um dos mais organizados da turma. Foi fácil de encontrar as coisas. Os pacotes foram claros de entender (só evitar letras maiúsculas nos pacotes, como em `br.com.comex.dao.main.itemPedido`).

As camadas estavam bem definidas. Usou bem os DAOs. E com pequenos ajustes, ficaria perfeito. Parabéns mesmo!!!

**Comment by lucasbiazin** [comment]
Obrigadaaaão!
